const meccanicoEdile = {
  "lista_rdi": [
    {
      "id_richiesta_intervento": "177",
      "progressivo_rdi": "38",
      "data_richiesta": "2022-08-24",
      "anno_rdi": "2022",
      "id_asset": "214",
      "marca": "LIEBHERR",
      "modello": "LHM 400",
      "matricola": "140753",
      "descrizione_asset": "GRU 25",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "GRU 25 - LIEBHERR - LHM 400",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": null,
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1661328287.000000",
      "uts_inserimento_odl": "1661328350.000000",
      "uts_in_esecuzione": "1661292000.000000",
      "uts_completata": "1661292000",
      "rdi_letta": "0",
      "rdi_letta_da": "giulio",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=177",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "198",
      "progressivo_rdi": "21",
      "data_richiesta": "2023-06-08",
      "anno_rdi": "2023",
      "id_asset": "320",
      "marca": "Marchetti",
      "modello": "MG144",
      "matricola": "3672",
      "descrizione_asset": "AUTOGRU MARCHETTI",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "AUTOGRU MARCHETTI - Marchetti - MG144",
      "descrizione": "ciao",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1686211907.000000",
      "uts_inserimento_odl": "1686212141.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": null,
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=198",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "199",
      "progressivo_rdi": "22",
      "data_richiesta": "2023-06-08",
      "anno_rdi": "2023",
      "id_asset": "320",
      "marca": "Marchetti",
      "modello": "MG144",
      "matricola": "3672",
      "descrizione_asset": "AUTOGRU MARCHETTI",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "AUTOGRU MARCHETTI - Marchetti - MG144",
      "descrizione": "ciao",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "B",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1686213879.000000",
      "uts_inserimento_odl": "1686214094.000000",
      "uts_in_esecuzione": "1688544063.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": null,
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=199",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "200",
      "progressivo_rdi": "23",
      "data_richiesta": "2023-06-15",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1686819590.000000",
      "uts_inserimento_odl": "1686820078.000000",
      "uts_in_esecuzione": "1686780000.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": null,
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=200",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "202",
      "progressivo_rdi": "25",
      "data_richiesta": "2023-06-20",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1687280449.000000",
      "uts_inserimento_odl": "1687281007.000000",
      "uts_in_esecuzione": "1687212000.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": null,
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=202",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "191",
      "progressivo_rdi": "14",
      "data_richiesta": "2023-05-15",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1684146765.000000",
      "uts_inserimento_odl": "1684157513.000000",
      "uts_in_esecuzione": "1687384800.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": null,
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=191",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "185",
      "progressivo_rdi": "8",
      "data_richiesta": "2023-05-02",
      "anno_rdi": "2023",
      "id_asset": "597",
      "marca": "TECI",
      "modello": "A 4 ALC",
      "matricola": "BS415308/14/010RIGHT",
      "descrizione_asset": "AUTOGRU MARCHETTI - FUNI",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "AUTOGRU MARCHETTI - FUNI - TECI - A 4 ALC",
      "descrizione": "Test extrabudget",
      "stato_rdi_sul_monitor": "completata",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1683038742.000000",
      "uts_inserimento_odl": "1683038758.000000",
      "uts_in_esecuzione": "1687816800.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": null,
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=185",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "206",
      "progressivo_rdi": "29",
      "data_richiesta": "2023-06-26",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "completata",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "-1",
      "uts_inserimento_rdi": "1687781239.000000",
      "uts_inserimento_odl": "1688043073.000000",
      "uts_in_esecuzione": "1687989600.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=206",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "195",
      "progressivo_rdi": "18",
      "data_richiesta": "2023-05-30",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "completata",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1685447824.000000",
      "uts_inserimento_odl": "1687530831.000000",
      "uts_in_esecuzione": "1689168820.000000",
      "uts_completata": "1689112800",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=195",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "207",
      "progressivo_rdi": "30",
      "data_richiesta": "2023-07-03",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "-1",
      "uts_inserimento_rdi": "1688388979.000000",
      "uts_inserimento_odl": "1688389178.000000",
      "uts_in_esecuzione": "1688390951.000000",
      "uts_completata": "1688335200",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=207",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "208",
      "progressivo_rdi": "31",
      "data_richiesta": "2023-07-04",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "-1",
      "uts_inserimento_rdi": "1688461903.000000",
      "uts_inserimento_odl": "1688461922.000000",
      "uts_in_esecuzione": "1688468918.000000",
      "uts_completata": "1688421600",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=208",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "209",
      "progressivo_rdi": "32",
      "data_richiesta": "2023-07-04",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "B",
      "intervento_in_emergenza": "-1",
      "uts_inserimento_rdi": "1688469866.000000",
      "uts_inserimento_odl": "1688469875.000000",
      "uts_in_esecuzione": "1688469905.000000",
      "uts_completata": "1691100000",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=209",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "211",
      "progressivo_rdi": "34",
      "data_richiesta": "2023-07-04",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "Test2",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "-1",
      "uts_inserimento_rdi": "1688485953.000000",
      "uts_inserimento_odl": "1688485989.000000",
      "uts_in_esecuzione": "1688546123.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=211",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "184",
      "progressivo_rdi": "7",
      "data_richiesta": "2023-04-27",
      "anno_rdi": "2023",
      "id_asset": "215",
      "marca": "LIEBHERR",
      "modello": "LHM 550",
      "matricola": "141457",
      "descrizione_asset": "GRU 26",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "GRU 26 - LIEBHERR - LHM 550",
      "descrizione": "Test extrabudget",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "B",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1682584744.000000",
      "uts_inserimento_odl": "1682584768.000000",
      "uts_in_esecuzione": "1689285600.000000",
      "uts_completata": "1689285600",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=184",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "213",
      "progressivo_rdi": "36",
      "data_richiesta": "2023-07-04",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1688486504.000000",
      "uts_inserimento_odl": "1689531320.000000",
      "uts_in_esecuzione": "1689531349.000000",
      "uts_completata": "1689458400",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=213",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "219",
      "progressivo_rdi": "42",
      "data_richiesta": "2023-07-12",
      "anno_rdi": "2023",
      "id_asset": "3",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 3",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 3",
      "descrizione": "tubo rotto",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1689150809.000000",
      "uts_inserimento_odl": "1689603911.000000",
      "uts_in_esecuzione": "1690322400.000000",
      "uts_completata": "1690322400",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=219",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "222",
      "progressivo_rdi": "45",
      "data_richiesta": "2023-08-18",
      "anno_rdi": "2023",
      "id_asset": "418",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "PS1 - IMPIANTO ARIA COMPRESSA",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "PS1 - IMPIANTO ARIA COMPRESSA",
      "descrizione": "foro",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1692348488.000000",
      "uts_inserimento_odl": "1692348567.000000",
      "uts_in_esecuzione": "1692348622.000000",
      "uts_completata": "1692309600",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=222",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "109",
      "progressivo_rdi": "6",
      "data_richiesta": "2020-10-21",
      "anno_rdi": "2020",
      "id_asset": "215",
      "marca": "LIEBHERR",
      "modello": "LHM 550",
      "matricola": "141457",
      "descrizione_asset": "GRU 26",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "GRU 26 - LIEBHERR - LHM 550",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": null,
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1603287259.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": null,
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=109",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "116",
      "progressivo_rdi": "10",
      "data_richiesta": "2020-11-16",
      "anno_rdi": "2020",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "Descrizione",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": null,
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1605526887.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": null,
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=116",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "117",
      "progressivo_rdi": "11",
      "data_richiesta": "2020-11-16",
      "anno_rdi": "2020",
      "id_asset": "398",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "PIAZZALE F",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "PIAZZALE F",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": null,
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1605531397.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": null,
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=117",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "139",
      "progressivo_rdi": "13",
      "data_richiesta": "2021-12-14",
      "anno_rdi": "2021",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1639497686.000000",
      "uts_inserimento_odl": "1639497773.000000",
      "uts_in_esecuzione": "1679266800.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=139",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "176",
      "progressivo_rdi": "37",
      "data_richiesta": "2022-08-24",
      "anno_rdi": "2022",
      "id_asset": "214",
      "marca": "LIEBHERR",
      "modello": "LHM 400",
      "matricola": "140753",
      "descrizione_asset": "GRU 25",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "GRU 25 - LIEBHERR - LHM 400",
      "descrizione": "Descrizione test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": null,
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1661327879.000000",
      "uts_inserimento_odl": "1661327929.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": null,
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=176",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "182",
      "progressivo_rdi": "5",
      "data_richiesta": "2023-04-12",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1681294858.000000",
      "uts_inserimento_odl": "1681295446.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "-1",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=182",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "192",
      "progressivo_rdi": "15",
      "data_richiesta": "2023-05-15",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1684152102.000000",
      "uts_inserimento_odl": "1684153393.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=192",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "212",
      "progressivo_rdi": "35",
      "data_richiesta": "2023-07-04",
      "anno_rdi": "2023",
      "id_asset": "6",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREE DIVERSE",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREE DIVERSE",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "odl_creato",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1688486093.000000",
      "uts_inserimento_odl": "1691161476.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=212",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "215",
      "progressivo_rdi": "38",
      "data_richiesta": "2023-07-11",
      "anno_rdi": "2023",
      "id_asset": "367",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 2 - ACQUA POTABILE",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "AREA DI ESPANSIONE 2 - ACQUA POTABILE",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1689089433.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "-1",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=215",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "216",
      "progressivo_rdi": "39",
      "data_richiesta": "2023-07-11",
      "anno_rdi": "2023",
      "id_asset": "367",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 2 - ACQUA POTABILE",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "AREA DI ESPANSIONE 2 - ACQUA POTABILE",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1689089433.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=216",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "217",
      "progressivo_rdi": "40",
      "data_richiesta": "2023-07-11",
      "anno_rdi": "2023",
      "id_asset": "239",
      "marca": "Audi",
      "modello": "A4",
      "matricola": "FC290NH",
      "descrizione_asset": "AUT Audi A4 FC290NH",
      "id_ambito": null,
      "descrizione_ambito": null,
      "nome_asset": "AUT Audi A4 FC290NH - Audi - A4",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "odl_creato",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "-1",
      "uts_inserimento_rdi": "1689091334.000000",
      "uts_inserimento_odl": "1689092547.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=217",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "218",
      "progressivo_rdi": "41",
      "data_richiesta": "2023-07-12",
      "anno_rdi": "2023",
      "id_asset": "239",
      "marca": "Audi",
      "modello": "A4",
      "matricola": "FC290NH",
      "descrizione_asset": "AUT Audi A4 FC290NH",
      "id_ambito": null,
      "descrizione_ambito": null,
      "nome_asset": "AUT Audi A4 FC290NH - Audi - A4",
      "descrizione": "test2",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "-1",
      "uts_inserimento_rdi": "1689149078.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=218",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "223",
      "progressivo_rdi": "46",
      "data_richiesta": "2023-09-19",
      "anno_rdi": "2023",
      "id_asset": "597",
      "marca": "TECI",
      "modello": "A 4 ALC",
      "matricola": "BS415308/14/010RIGHT",
      "descrizione_asset": "AUTOGRU MARCHETTI - FUNI",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "AUTOGRU MARCHETTI - FUNI - TECI - A 4 ALC",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "B",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695133732.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=223",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "225",
      "progressivo_rdi": "48",
      "data_richiesta": "2023-09-19",
      "anno_rdi": "2023",
      "id_asset": "6",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREE DIVERSE",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREE DIVERSE",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "B",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695134197.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=225",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "227",
      "progressivo_rdi": "1",
      "data_richiesta": "2023-09-20",
      "anno_rdi": "2023",
      "id_asset": "6",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREE DIVERSE",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREE DIVERSE",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "B",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695160800.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=227",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "229",
      "progressivo_rdi": "50",
      "data_richiesta": "2023-09-20",
      "anno_rdi": "2023",
      "id_asset": "6",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREE DIVERSE",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREE DIVERSE",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "B",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695218435.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=229",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "235",
      "progressivo_rdi": "56",
      "data_richiesta": "2023-09-20",
      "anno_rdi": "2023",
      "id_asset": "6",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREE DIVERSE",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREE DIVERSE",
      "descrizione": "aswsw",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695218894.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "dvadmin",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=235",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "236",
      "progressivo_rdi": "57",
      "data_richiesta": "2023-09-25",
      "anno_rdi": "2023",
      "id_asset": "6",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREE DIVERSE",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREE DIVERSE",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695636631.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=236",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "237",
      "progressivo_rdi": "58",
      "data_richiesta": "2023-09-25",
      "anno_rdi": "2023",
      "id_asset": "6",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREE DIVERSE",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREE DIVERSE",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695650820.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "dvadmin",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=237",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "238",
      "progressivo_rdi": "59",
      "data_richiesta": "2023-09-25",
      "anno_rdi": "2023",
      "id_asset": "6",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREE DIVERSE",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREE DIVERSE",
      "descrizione": "t",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "B",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695650846.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "dvadmin",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=238",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "239",
      "progressivo_rdi": "60",
      "data_richiesta": "2023-09-25",
      "anno_rdi": "2023",
      "id_asset": "6",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREE DIVERSE",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREE DIVERSE",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695650913.000000",
      "uts_inserimento_odl": "1695655159.000000",
      "uts_in_esecuzione": "1695592800.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=239",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "240",
      "progressivo_rdi": "61",
      "data_richiesta": "2023-09-25",
      "anno_rdi": "2023",
      "id_asset": "6",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREE DIVERSE",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREE DIVERSE",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "B",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695650924.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "dvadmin",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=240",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "241",
      "progressivo_rdi": "62",
      "data_richiesta": "2023-09-25",
      "anno_rdi": "2023",
      "id_asset": "594",
      "marca": "DIEPA",
      "modello": "DIEPA X 53 (PZ371)2-3-TEUFELBERGER 1-4",
      "matricola": "DN1400050-RIGHT(2)-DN1400051LEFT(3)-187967-RIGHT(1)187968-LEFT84)",
      "descrizione_asset": "GRU 27 - FUNI",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "GRU 27 - FUNI - DIEPA - DIEPA X 53 (PZ371)2-3-TEUFELBERGER 1-4",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "in_esecuzione",
      "codice_grado_urgenza": "M",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1695655754.000000",
      "uts_inserimento_odl": "1696254414.000000",
      "uts_in_esecuzione": "1696197600.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=241",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "242",
      "progressivo_rdi": "63",
      "data_richiesta": "2023-10-04",
      "anno_rdi": "2023",
      "id_asset": "215",
      "marca": "LIEBHERR",
      "modello": "LHM 550",
      "matricola": "141457",
      "descrizione_asset": "GRU 26",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "GRU 26 - LIEBHERR - LHM 550",
      "descrizione": "test",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1696405648.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=242",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "243",
      "progressivo_rdi": "64",
      "data_richiesta": "2023-10-18",
      "anno_rdi": "2023",
      "id_asset": "1",
      "marca": null,
      "modello": null,
      "matricola": null,
      "descrizione_asset": "AREA DI ESPANSIONE 1",
      "id_ambito": "1",
      "descrizione_ambito": "Edile",
      "nome_asset": "AREA DI ESPANSIONE 1",
      "descrizione": "descrizione breve",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "A",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1697636642.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=243",
      "presa_visione_automatica": -1
    },
    {
      "id_richiesta_intervento": "245",
      "progressivo_rdi": "66",
      "data_richiesta": "2023-11-06",
      "anno_rdi": "2023",
      "id_asset": "214",
      "marca": "LIEBHERR",
      "modello": "LHM 400",
      "matricola": "140753",
      "descrizione_asset": "GRU 25",
      "id_ambito": "2",
      "descrizione_ambito": "Meccanico",
      "nome_asset": "GRU 25 - LIEBHERR - LHM 400",
      "descrizione": "descrizione breve",
      "stato_rdi_sul_monitor": "inserita",
      "codice_grado_urgenza": "B",
      "intervento_in_emergenza": "0",
      "uts_inserimento_rdi": "1699287151.000000",
      "uts_inserimento_odl": "0.000000",
      "uts_in_esecuzione": "0.000000",
      "uts_completata": "0",
      "rdi_letta": "0",
      "rdi_letta_da": "apetrosino",
      "url_rdi": "http://localhost/hypersapir/hyper/mainpage.php?section=man_richieste_intervento&action=view&key_modulo=245",
      "presa_visione_automatica": -1
    }
  ],
  "azienda_corrente": "S",
  "ambiti_correnti": [],
  "presa_visione_automatica": -1
}

module.exports = { meccanicoEdile };